[package]
name = "inference"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["ndarray"] }
burn-derive = "0.15.0"
burn-import = { version = "0.15.0", features = ["pytorch"] }
