
name: Manual Release
run-name: Release build for ${{ github.actor }} 🚀
on: [workflow_dispatch]
# target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
jobs:
  WindowsRelease:
    name: Windows build for release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get toolchain
        run: rustup target add x86_64-pc-windows-gnu
      - name: Get MinGW
        run: sudo apt install gcc-mingw-w64
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
  LinuxRelease:
    name: Linux build for release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get toolchain
        run: rustup target add x86_64-unknown-linux-musl
      - name: Get MinGW
        run: sudo apt install musl-tools
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl
