
name: Manual Release
run-name: Release build for ${{ github.actor }} 🚀
on: [workflow_dispatch]
jobs:
  Release:
    name: Build for release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get toolchain
        run: rustup target add ${{ matrix.target }}
      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
