
name: Manual Release
run-name: Release build for ${{ github.actor }} 🚀
on: [workflow_dispatch]
jobs:
  MacRelease:
    name: Mac build for release
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact-macos
          path: target/release/cherrylipsync
  WindowsRelease:
    name: Windows build for release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get toolchain
        run: rustup target add x86_64-pc-windows-gnu
      - name: Get MinGW
        run: sudo apt install gcc-mingw-w64
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact-win
          path: target/x86_64-pc-windows-gnu/release/cherrylipsync.exe
  LinuxRelease:
    name: Linux build for release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get toolchain
        run: rustup target add x86_64-unknown-linux-musl
      - name: Get Musl
        run: sudo apt install musl-tools
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact-linux
          path: target/x86_64-unknown-linux-musl/release/cherrylipsync
  Upload:
    name: Save artifacts
    runs-on: ubuntu-latest
    needs: [MacRelease, WindowsRelease, LinuxRelease]
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-artifact-*
      - name: Show what we have
        run: ls -R
